package com.NexStock.controller;

import java.util.ArrayList;

import com.NexStock.model.Admin;
import com.NexStock.model.Cashier;
import com.NexStock.model.User;
import com.NexStock.security.Password_Generator;

import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.scene.control.Alert.AlertType;
import javafx.stage.Stage;

import javafx.event.ActionEvent;

public class SceneNewController {

    @FXML
    private TextField fullname;
    @FXML
    private TextField username;
    @FXML
    private PasswordField passwordbutton;
    @FXML
    private PasswordField confirmpasswordbutton;
    @FXML
    private TextField email;
    @FXML
    private Label labelshow;

    @FXML
    private CheckBox checkboxtick;

    @FXML
    public void initilize() {
        checkboxtick.getContentDisplay();
    }

    @FXML
    private Button createaccountbutton;

    Password_Generator p1 = new Password_Generator();

    @FXML
    public void createaccount(ActionEvent event) {

        String enteredfullname = fullname.getText();
        fullname.isFocused();
        String usernameEntered = username.getText();
        username.isFocused();
        String emailentered = email.getText();
        email.isFocused();

        boolean autoGenerated = false;// check it is required or not (Depend on user choice)
        if (passwordbutton.getText().isEmpty()) {
            String generated = p1.generate(12);
            passwordbutton.setText(generated);
            confirmpasswordbutton.setText(generated);
            autoGenerated = true;
        }

        if (!passwordbutton.getText().equals(confirmpasswordbutton.getText())) {
            labelshow.setText("both Passwords not match!");
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.show();
            alert.showAndWait();
            return; // stop here, don't create account bcz password does't match
        }

        ArrayList<User> users = new ArrayList<>();
        if (autoGenerated) {
            users.add(new Admin(emailentered, usernameEntered, emailentered, enteredfullname, usernameEntered,
                    emailentered));
            labelshow.setText("  Account created ....... by auto-generated password!");

            this.switchtoaddproduct(event);
        } else {
            users.add(new Cashier(enteredfullname, usernameEntered, emailentered, usernameEntered, emailentered));
            labelshow.setText("Account created successfully!");

            this.switchtoaddproduct(event);
        }

        for (User user : users) {
            user.toFilestore();
        }
    }

    @FXML
    public void switchtoaddproduct(ActionEvent e) {
        Stage stage = (Stage) ((Button) e.getSource()).getScene().getWindow();// creating new stage from button event
        Sceneswitches.setStage(stage);
        Sceneswitches.switchto("addProduct.fxml");
    }

}
