package com.NexStock.controller;

import java.util.ArrayList;
import java.util.logging.FileHandler;

import com.NexStock.FileHandler.fileIO;
import com.NexStock.model.Admin;
import com.NexStock.model.Cashier;
import com.NexStock.model.User;
import com.NexStock.security.Password_Generator;

import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.stage.Stage;

import javafx.event.ActionEvent;

public class createAccount {

    @FXML
    private TextField fullname;
    @FXML
    private TextField username;
    @FXML
    private PasswordField passwordbutton;
    @FXML
    private PasswordField confirmpasswordbutton;
    @FXML
    private TextField email;
    @FXML
    private Label labelshow;

    @FXML
    private CheckBox checkboxtick;

    @FXML
    public void initialize() {
        checkboxtick.setSelected(true);
        checkboxtick.getContentDisplay();
    }

    @FXML
    private Button createaccountbutton;

    @FXML
    public void switchtoaddProduct(ActionEvent eventcopy) {
        Stage stage = (Stage) ((Button) eventcopy.getSource()).getScene().getWindow();// creating new stage from button
        // event
        Sceneswitches.setStage(stage);
        Sceneswitches.now_switchin("addProduct.fxml");
    }

    Password_Generator p1 = new Password_Generator();

    fileIO IO = new fileIO();
    boolean accountcreated = false;

    @FXML
    public void createaccount(ActionEvent event) {

        String enteredfullname = fullname.getText();

        String usernameEntered = username.getText();

        String emailentered = email.getText();

        boolean autoGenerated = false;// check it is required or not (Depend on user choice)
        if (passwordbutton.getText().isEmpty()) {
            String generated = p1.generate(12);
            passwordbutton.setText(generated);
            confirmpasswordbutton.setText(generated);
            autoGenerated = true;// now i ll check this before creating account
        }

        if (!passwordbutton.getText().equals(confirmpasswordbutton.getText())) {
            labelshow.setText("both Passwords not match!");
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setContentText("Passwords do not match. Please try again.");
            alert.setHeaderText("Error");
            alert.setResizable(false);
            alert.setTitle("Password Mismatch");
            alert.showAndWait();

            return; // stop here, don't create account bcz password does't match
        }

        ArrayList<User> users = new ArrayList<>();

        if (usernameEntered.trim().isEmpty() || passwordbutton.getText().length() < 8) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setContentText("Username or Password is empty or invalid");
            alert.setHeaderText("Error");
            alert.setResizable(false);
            alert.showAndWait();
            return;
        } else if (passwordbutton.getText().matches("[0-9]+") || passwordbutton.getText().matches("[a-zA-Z]+")) {// check
                                                                                                                 // that
                                                                                                                 // it
            // contains only
            // digits
            Alert alert = new Alert(Alert.AlertType.WARNING);
            alert.setResizable(false);
            alert.setContentText("Password should contain at least one letter and special character");
            alert.setHeaderText("Weak Password");
            alert.setTitle("Password Strength");
            alert.showAndWait();
            return;

        }

        if (autoGenerated) {
            if (checkboxtick.isSelected()) {
                users.add(new Admin(enteredfullname, usernameEntered, emailentered,
                        passwordbutton.getText(), confirmpasswordbutton.getText(), "standard"));
                labelshow.setText("Successful auto password used");
                accountcreated = true;

            } else if (!checkboxtick.isSelected()) {
                users.add(new Cashier(enteredfullname, usernameEntered, emailentered,
                        passwordbutton.getText(), confirmpasswordbutton.getText()));
                labelshow.setText("successful auto password used");
                accountcreated = true;

            }
        } else {
            if (checkboxtick.isSelected()) {
                users.add(new Admin(enteredfullname, usernameEntered, emailentered,
                        passwordbutton.getText(), confirmpasswordbutton.getText(), "standard"));
                labelshow.setText(" Admin Account created .......");
                accountcreated = true;

            } else if (!checkboxtick.isSelected()) {
                users.add(new Cashier(enteredfullname, usernameEntered, emailentered,
                        passwordbutton.getText(), confirmpasswordbutton.getText()));
                labelshow.setText("Cashier Account created successfully!");
                accountcreated = true;

            }

        }
        for (User u : users) {
            if (u instanceof Admin) {
                Admin ad = (Admin) u;
                IO.filewriter("User.txt", ad.tofile());
            } else if (u instanceof Cashier ca) {// this is used in modern java so, i used both ways
                IO.filewriter("User.txt", ca.tofile());
            }

        }
        if (accountcreated)
            this.switchtoaddProduct(event);
    }
}
