package com.NexStock.controller;

import java.util.ArrayList;
import java.util.logging.FileHandler;

import com.NexStock.FileHandler.fileIO;
import com.NexStock.model.Admin;
import com.NexStock.model.Cashier;
import com.NexStock.model.User;
import com.NexStock.security.Password_Generator;

import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.stage.Stage;

import javafx.event.ActionEvent;

public class createAccount {

    @FXML
    private TextField fullname;
    @FXML
    private TextField username;
    @FXML
    private PasswordField passwordbutton;
    @FXML
    private PasswordField confirmpasswordbutton;
    @FXML
    private TextField email;
    @FXML
    private Label labelshow;

    @FXML
    private CheckBox checkboxtick;

    @FXML
    public void initialize() {
        checkboxtick.setSelected(true);
        checkboxtick.getContentDisplay();
        fullname.requestFocus();
        fullname.setOnAction(event -> username.requestFocus());
        username.setOnAction(event -> passwordbutton.requestFocus());
        passwordbutton.setOnAction(event -> confirmpasswordbutton.requestFocus());
        confirmpasswordbutton.setOnAction(event -> email.requestFocus());
    }

    Password_Generator p1 = new Password_Generator();

    fileIO IO = new fileIO();
    boolean accountcreated = false;

    private void showAlert(String title, String message, String header) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle(title);
        alert.setHeaderText(header);
        alert.setContentText(message);
        alert.resizableProperty().set(false);
        alert.showAndWait();
    }

    @FXML
    public void createaccount(ActionEvent event) {

        String enteredfullname = fullname.getText();
        String usernameEntered = username.getText();
        String emailentered = email.getText();

        boolean autoGenerated = false;// check it is required or not (Depend on user choice)
        if (passwordbutton.getText().isEmpty()) {
            String generated = p1.generate(12);
            passwordbutton.setText(generated);
            confirmpasswordbutton.setText(generated);
            autoGenerated = true;// now i ll check this before creating account
        }

        for (User user_current : IO.readList_Users) {

            if (user_current.getUserName().equals(usernameEntered)) {
                showAlert("Error", "Username already exists. Please choose a different username.",
                        "Duplicate Username");
            }
        }

        if (!passwordbutton.getText().equals(confirmpasswordbutton.getText())) {
            labelshow.setText("both Passwords not match!");
            showAlert("Password Mismatch", "Passwords do not match. Please try again.", "Password Error");

            return; // stop here, don't create account bcz password does't match
        }

        ArrayList<User> users = new ArrayList<>();

        if (usernameEntered.trim().isEmpty() || passwordbutton.getText().length() < 8) {

            showAlert("Error", "Username cannot be empty and Password must be at least 8 characters long.",
                    "Input Error");

        } else if (passwordbutton.getText().matches("[0-9]+") || passwordbutton.getText().matches("[a-zA-Z]+")) {// check
            // that
            // it
            // contains only
            // digits
            showAlert("Password Strength", "Password should contain at least one letter and special character",
                    "Weak Password");
            Alert alert = new Alert(Alert.AlertType.WARNING);
            alert.setResizable(false);
            alert.setContentText("Password should contain at least one letter and special character");
            alert.setHeaderText("Weak Password");
            alert.setTitle("Password Strength");
            alert.showAndWait();
            return;

        }
        if (autoGenerated) {
            if (checkboxtick.isSelected()) {
                users.add(new Admin(enteredfullname, usernameEntered, emailentered,
                        passwordbutton.getText(), confirmpasswordbutton.getText(), "standard"));
                labelshow.setText("Successful auto password used");
                accountcreated = true;

            } else if (!checkboxtick.isSelected()) {
                users.add(new Cashier(enteredfullname, usernameEntered, emailentered,
                        passwordbutton.getText(), confirmpasswordbutton.getText()));
                labelshow.setText("successful auto password used");
                accountcreated = true;

            }
        } else {
            if (checkboxtick.isSelected()) {
                users.add(new Admin(enteredfullname, usernameEntered, emailentered,
                        passwordbutton.getText(), confirmpasswordbutton.getText(), "standard"));
                labelshow.setText(" Admin Account created .......");
                accountcreated = true;

            } else if (!checkboxtick.isSelected()) {
                users.add(new Cashier(enteredfullname, usernameEntered, emailentered,
                        passwordbutton.getText(), confirmpasswordbutton.getText()));
                labelshow.setText("Cashier Account created successfully!");
                accountcreated = true;

            }

        }
        for (User u : users) {
            if (u instanceof Admin) {
                Admin ad = (Admin) u;
                IO.filewriter("User.txt", ad.tofile());
            } else if (u instanceof Cashier ca) {// this is used in modern java so, i used both ways
                IO.filewriter("User.txt", ca.tofile());
            }

        }

        if (accountcreated) {
            System.out.println("Changing Scene ... ");
            Stage stage = (Stage) ((Button) event.getSource()).getScene().getWindow();
            Sceneswitches.setStage(stage);
            Sceneswitches.now_switchin("login.fxml");

        }
    }
}