package com.NexStock.controller;

import com.NexStock.model.Admin;
import com.NexStock.security.Password_Generator;
import com.NexStock.security.Password_Hasher;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;


public class SceneNewController {

    @FXML
    private TextField fullname;
    @FXML
    private TextField username;
    @FXML
    private PasswordField passwordbutton;
    @FXML
    private PasswordField confirmpasswordbutton;
    @FXML
    private TextField email;
    @FXML
    private Label labelshow;

    @FXML
    private Button createaccountbutton;

    Password_Generator p1 = new Password_Generator();

    @FXML
    public void createaccount() {

        String enteredfullname = fullname.getText();
        String usernameEntered = username.getText();
        String emailentered = email.getText();


        boolean autoGenerated = false;//check it is required or not
        if (passwordbutton.getText().isEmpty()) {
            String generated = p1.generate(12);
            passwordbutton.setText(generated);
            confirmpasswordbutton.setText(generated);
            autoGenerated = true;
        }

        if (!passwordbutton.getText().equals(confirmpasswordbutton.getText())) {
            labelshow.setText("Passwords do not match!");
            return; // stop here, don't create account
        }


        Admin u1 = new Admin(
                enteredfullname,
                usernameEntered,
                emailentered,
                passwordbutton.getText(),
                confirmpasswordbutton.getText(),
                "root"
        );


        if (autoGenerated) {
            labelshow.setText("Account created with auto-generated password!");
        } else {
            labelshow.setText("Account created successfully!");
        }
    }

}

